services:
  - type: web
    name: srt-autobook-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
